name = 'alt:V Server'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'freeroam'
website = 'example.com'
language = 'en'
description = 'alt:V Server'
modules = ['csharp-module', 'js-module']
resources = [
	"gamemode"
]
debug = true